// actionTypes.js
export const SET_CURRENT_TAB = 'SET_CURRENT_TAB';
export const SET_VIDEO_LENGTH = 'SET_VIDEO_LENGTH';
export const SET_VOLUME = 'SET_VOLUME';
export const SET_VIDEO_PLAYING = 'SET_VIDEO_PLAYING';
export const SET_CURRENT_TIME = 'SET_CURRENT_TIME';
export const SET_CURRENT_TIME_SEEKBAR = 'SET_CURRENT_TIME_SEEKBAR';
export const SET_PLAYBACK_SPEED = 'SET_PLAYBACK_SPEED';
export const SET_CROPPER_ACTIVE = 'SET_CROPPER_ACTIVE';
export const SET_CROPPER_ASPECT_RATIO = 'SET_CROPPER_ASPECT_RATIO';
export const SET_CROPPER_POSITION = 'SET_CROPPER_POSITION';
export const SET_CROPPER_SIZE = 'SET_CROPPER_SIZE';
export const ADD_CUT = 'ADD_CUT';
export const REMOVE_CUT = 'REMOVE_CUT';
export const SYNC_CROPPER = 'SYNC_CROPPER';
export const SET_CURRENT_CUT = 'SET_CURRENT_CUT';
